package lt.vu.mybatis.dao;

import lt.vu.mybatis.model.Room;
import org.mybatis.cdi.Mapper;

import java.util.List;

@Mapper
public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Mon Apr 08 21:01:54 EEST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Mon Apr 08 21:01:54 EEST 2024
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Mon Apr 08 21:01:54 EEST 2024
     */
    Room selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Mon Apr 08 21:01:54 EEST 2024
     */
    List<Room> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Mon Apr 08 21:01:54 EEST 2024
     */
    int updateByPrimaryKey(Room record);
}