package lt.vu.mybatis.dao;

import java.util.List;
import lt.vu.mybatis.model.Room;

public interface RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sun Mar 24 18:47:14 EET 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sun Mar 24 18:47:14 EET 2024
     */
    int insert(Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.ROOM
     *
     * @mbg.generated Sun Mar 24 18:47:14 EET 2024
     */
    List<Room> selectAll();
}