package lt.vu.mybatis.model;

public class Member {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.ID
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.NAME
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MEMBER.TEAM_ID
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    private Integer teamId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.ID
     *
     * @return the value of PUBLIC.MEMBER.ID
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.ID
     *
     * @param id the value for PUBLIC.MEMBER.ID
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.NAME
     *
     * @return the value of PUBLIC.MEMBER.NAME
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.NAME
     *
     * @param name the value for PUBLIC.MEMBER.NAME
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MEMBER.TEAM_ID
     *
     * @return the value of PUBLIC.MEMBER.TEAM_ID
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MEMBER.TEAM_ID
     *
     * @param teamId the value for PUBLIC.MEMBER.TEAM_ID
     *
     * @mbg.generated Mon Apr 08 21:44:06 EEST 2024
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }
}