package lt.vu.mybatis.model;

public class Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Mar 24 18:47:14 EET 2024
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.ROOM.ID
     *
     * @return the value of PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Mar 24 18:47:14 EET 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.ROOM.ID
     *
     * @param id the value for PUBLIC.ROOM.ID
     *
     * @mbg.generated Sun Mar 24 18:47:14 EET 2024
     */
    public void setId(Long id) {
        this.id = id;
    }
}